// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nybvcmrnjpmcfzzohfhi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im55YnZjbXJuanBtY2Z6em9oZmhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk3OTkxNjQsImV4cCI6MjA1NTM3NTE2NH0.mRPej9UBBT-P6C0XdJwDqrWfOyOrvtB5GOsLZ7uC4zk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);